export const authConstraints = {
    SIGNUP_REQUEST: "SIGNUP_REQUEST",
    SIGNUP_FAILED: "SIGNUP_FAILED",
    SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
    SIGNIN_REQUEST: "SIGNIN_REQUEST",
    SIGNIN_FAILED: "SIGNIN_FAILED",
    SIGNIN_SUCCESS: "SIGNIN_SUCCESS",
    SIGNOUT_REQUEST: "SIGNOUT_REQUEST",
    SIGNOUT_FAILED: "SIGNOUT_FAILED",
    SIGNOUT_SUCCESS: "SIGNOUT_SUCCESS",
    CHECKING_LOGIN_STATUS: "CHECKING_LOGIN_STATUS",
    USER_LOGGEDIN: "USER_LOGGEDIN",
    USER_NOT_FOUND: "USER_NOT_FOUND"

}

export const categoryConstraints = {
    ADD_NEW_CATEGORY_REQUEST: "ADD_NEW_CATEGORY_REQUEST",
    ADD_NEW_CATEGORY_FAILED: "ADD_NEW_CATEGORY_FAILED",
    ADD_NEW_CATEGORY_SUCCESS: "ADD_NEW_CATEGORY_SUCCESS",
    GET_ALL_CATEGORY_REQUEST: "GET_ALL_CATEGORY_REQUEST",
    GET_ALL_CATEGORY_FAILED: "GET_ALL_CATEGORY_FAILED",
    GET_ALL_CATEGORY_SUCCESS: "GET_ALL_CATEGORY_SUCCESS",
    DELETE_CATEGORY_REQUEST: "DELETE_CATEGORY_REQUEST",
    DELETE_CATEGORY_FAILED: "DELETE_CATEGORY_FAILED",
    DELETE_CATEGORY_SUCCESS: "DELETE_CATEGORY_SUCCESS",
    GET_CATEGORY_INFO_REQUEST: "GET_CATEGORY_INFO_REQUEST",
    GET_CATEGORY_INFO_FAILED: "GET_CATEGORY_INFO_FAILED",
    GET_CATEGORY_INFO_SUCCESS: "GET_CATEGORY_INFO_SUCCESS",
    EDIT_CATEGORY_REQUEST: "EDIT_CATEGORY_REQUEST",
    EDIT_CATEGORY_FAILED: "EDIT_CATEGORY_FAILED",
    EDIT_CATEGORY_SUCCESS: "EDIT_CATEGORY_SUCCESS",
};

export const productConstraints = {
    ADD_NEW_PRODUCT_REQUEST: "ADD_NEW_PRODUCT_REQUEST",
    ADD_NEW_PRODUCT_FAILED: "ADD_NEW_PRODUCT_FAILED",
    ADD_NEW_PRODUCT_SUCCESS: "ADD_NEW_PRODUCT_SUCCESS",
    GET_ALL_PRODUCT_REQUEST: "GET_ALL_PRODUCT_REQUEST",
    GET_ALL_PRODUCT_FAILED: "GET_ALL_PRODUCT_FAILED",
    GET_ALL_PRODUCT_SUCCESS: "GET_ALL_PRODUCT_SUCCESS",
    EDIT_PRODUCT_REQUEST: "EDIT_PRODUCT_REQUEST",
    EDIT_PRODUCT_FAILED: "EDIT_PRODUCT_FAILED",
    EDIT_PRODUCT_SUCCESS: "EDIT_PRODUCT_SUCCESS",
    DELETE_PRODUCT_REQUEST: "DELETE_PRODUCT_REQUEST",
    DELETE_PRODUCT_FAILED: "DELETE_PRODUCT_FAILED",
    DELETE_PRODUCT_SUCCESS: "DELETE_PRODUCT_SUCCESS",
}