export const authConstraints = {
    SIGNUP_REQUEST: "SIGNUP_REQUEST",
    SIGNUP_FAILED: "SIGNUP_FAILED",
    SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
    SIGNIN_REQUEST: "SIGNIN_REQUEST",
    SIGNIN_FAILED: "SIGNIN_FAILED",
    SIGNIN_SUCCESS: "SIGNIN_SUCCESS",
    SIGNOUT_REQUEST: "SIGNOUT_REQUEST",
    SIGNOUT_FAILED: "SIGNOUT_FAILED",
    SIGNOUT_SUCCESS: "SIGNOUT_SUCCESS",
    CHECKING_LOGIN_STATUS: "CHECKING_LOGIN_STATUS",
    USER_LOGGEDIN: "USER_LOGGEDIN",
    USER_NOT_FOUND: "USER_NOT_FOUND"

}

export const categoryConstraints = {
    ADD_NEW_CATEGORY_REQUEST: "ADD_NEW_CATEGORY_REQUEST",
    ADD_NEW_CATEGORY_FAILED: "ADD_NEW_CATEGORY_FAILED",
    ADD_NEW_CATEGORY_SUCCESS: "ADD_NEW_CATEGORY_SUCCESS",
}