export const authConstraints = {
    SIGNUP_REQUEST: "SIGNUP_REQUEST",
    SIGNUP_FAILED: "SIGNUP_FAILED",
    SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
    SIGNIN_REQUEST: "SIGNIN_REQUEST",
    SIGNIN_FAILED: "SIGNIN_FAILED",
    SIGNIN_SUCCESS: "SIGNIN_SUCCESS",
    SIGNOUT_REQUEST: "SIGNOUT_REQUEST",
    SIGNOUT_FAILED: "SIGNOUT_FAILED",
    SIGNOUT_SUCCESS: "SIGNOUT_SUCCESS",
}